account/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.RegisterView.as_view(), name='register'),
]

discovery/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'account/', include('account.urls', namespace='account')),
    url(r'^files/', include('fileconnector.urls', namespace='files')),
    url(r'^spark/', include('sparkjob.urls', namespace='spark')),
    url(r'^connectors/', include('dbconnector.urls', namespace='connector')),
    url(r'^inventory/', include('datainventory.urls', namespace='inventory')),
    url(r'^services/', include('services.urls', namespace='services')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fileconnector/urls.py
from django.conf.urls import url

from fileconnector import views


urlpatterns = [
    url(r'^$', views.file_list, name='list'),
    url(r'^upload/$', views.file_upload, name='upload'),
    url(r'^(?P<id>\d+)/$', views.file_detail, name='detail'),
    url(r'^(?P<id>\d+)/edit/$', views.file_edit, name='edit'),
    url(r'^(?P<id>\d+)/delete/$', views.file_list, name='delete'),
]

sparkjob/urls.py
from django.conf.urls import url

from sparkjob.viewsets import entity_detail, csv_jobs, jdbc_jobs

urlpatterns = [
    url(r'^(?P<id>\d+)/$', entity_detail, name='detail'),
    url(r'^csv/$', csv_jobs, name='csv'),
    url(r'^jdbc/$', jdbc_jobs, name='jdbc'),
]

fileconnector/models.py
from django.db import models


class FileModel(models.Model):
    file = models.FileField(null=True, blank=True)
    description = models.TextField()

    def __str__(self):
        return self.description

fileconnector/forms.py
from django.forms import ModelForm, CharField, Textarea, ClearableFileInput, FileField, NumberInput

from fileconnector.models import FileModel


class FileForm(ModelForm):
    file = FileField(widget=ClearableFileInput(
        attrs={
            'class': 'form-control'
        }
    ))
    description = CharField(widget=Textarea(
        attrs={
            'class': 'form-control'
        }
    ))

    class Meta:
        model = FileModel
        fields = ["file", "description"]

fileconnector/views.py
import csv, json, uuid
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from fileconnector.forms import FileForm
from fileconnector.models import FileModel


def file_detail(request, id):
    instance = get_object_or_404(FileModel, id=id)
    delimiter = request.GET.get('delimiter', ',')
    schema, data = read_csv(instance.file.path, delimiter)
    context = {
        'id': id,
        'instance': instance,
        'schema_str': json.dumps(schema),
        'uuid': str(uuid.uuid1()).replace('-', '_'),
        'data': json.dumps(data),
        'delimiter': delimiter
    }
    return render(request, 'fileconnector/file_detail.html', context)


def file_upload(request):
    form = FileForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return redirect(reverse('files:detail', args=[instance.id]))
    context = {
        'home_tab': '',
        'file_tab': 'active',
        'db_tab': '',
        'form': form
    }
    return render(request, 'fileconnector/form.html', context)


def read_csv(path, delimiter):
    with open(path) as csv_file:
        reader = csv.reader(csv_file, delimiter=delimiter)
        header = next(reader)
        cols = [{title: 'string'} for title in header]
        rows = []
        for row in csv_file:
            rows.append(dict(zip(header, row.split(delimiter))))
        return cols, rows

def file_list(request):
    queryset = FileModel.objects.all()
    context = {
        'object_list': queryset
    }
    return render(request, 'fileconnector/file_list.html', context)



def file_edit(request, id):
    instance = get_object_or_404(FileModel, id=id)
    form = FileForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return redirect(reverse('files:detail', args=[instance.id]))
    context = {
        'form': form
    }
    return render(request, 'fileconnector/form.html', context)

fileconnector/templates/fileconnector/file_detail.html
{% extends 'base.html' %}
{% block body %}
    <form method="get" action="{% url 'files:detail' id %}">
        <input type="text" id="delimter" name="delimiter" value="{{ delimiter }}"><br>
        <input type="submit" value="Delimiter"><br>
    </form>
    <label>{{ instance.file.name }}</label><br>
    <label>{{ uuid }}</label><br>
    <table class="table table-striped" id="sampleTable"><tbody></tbody></table>
    <form method="post" action="{% url 'spark:csv' %}">
        {% csrf_token %}
        <input type="hidden" id="file" name="file" value="{{ instance.file.name }}">
        <input type="hidden" id="name" name="name" value="{{ uuid }}">
        <input type="text" id="description" name="description" value="{{ instance.description }}"><br>
        <input type="hidden" id="schema" name="schema" value="{{ schema_str }}">
        <input type="hidden" id="data" value="{{ data }}">
        <input type="submit" value="Create Data Set"><br>
    </form>
    <script type="text/javascript">
        $(function() {
            addTable($.parseJSON($("input#data").val()),
                    $("table#sampleTable"),
                    $("input#schema"));
        });
    </script>
{% endblock %}

fileconnector/templates/fileconnector/file_list.html
{% extends 'base.html' %}
{% block body %}
    <div>
    {% for obj in object_list %}
        <a href="{% url 'files:detail' obj.id %}">
        {{ obj.title }} - {{ obj.id }}</a>
        {{ obj.file }}<br/>
    {% endfor %}
    </div>
{% endblock %}

fileconnector/templates/fileconnector/form.html
{% extends 'base.html' %}
{% block body %}
    <div class="col">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Upload File">
        </form>
    </div>
{% endblock %}