account/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.RegisterView.as_view(), name='register'),
]

datainventory/urls.py
from django.conf.urls import url

from datainventory import views
from datainventory import viewsets

app_name = 'inventory'
urlpatterns = [
    url(r'^$', views.inventory_list, name='data_list'),
    url(r'^(?P<id>\d+)/$', views.inventory_detail, name='data_detail'),
    url(r'^api/$', viewsets.inventory_list),
    url(r'^api/(?P<id>\d+)/$', viewsets.inventory_detail)
]

discovery/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'account/', include('account.urls', namespace='account')),
    url(r'^files/', include('fileconnector.urls', namespace='files')),
    url(r'^spark/', include('sparkjob.urls', namespace='spark')),
    url(r'^connectors/', include('dbconnector.urls', namespace='connector')),
    url(r'^inventory/', include('datainventory.urls', namespace='inventory')),
    url(r'^services/', include('services.urls', namespace='services')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

datainventory/models.py
from django.db import models


class InventoryModel(models.Model):
    name = models.CharField(max_length=256)
    schema = models.TextField()
    sample = models.TextField(default='')
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

datainventory/views.py
import json

from django.shortcuts import render, get_object_or_404

from datainventory.models import InventoryModel


def inventory_list(request):
    object_list = InventoryModel.objects.all()
    context = {
        'home_tab': 'active',
        'file_tab': '',
        'db_tab': '',
        'object_list': object_list
    }
    return render(request, 'datainventory/list.html', context=context)


def inventory_detail(request, id):
    instance = get_object_or_404(InventoryModel, id=id)
    context = {
        'instance': instance,
        'sample': json.loads(instance.sample)
    }
    return render(request, 'datainventory/detail.html', context)

datainventory/templates/datainventory/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}base{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <script src="{% static 'datainventory/js/main.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'discovery/style.css' %}"/>
</head>
<body>
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <a class="navbar-brand" href="#">
            <img src="http://getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top">
            Navbar
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarcollapseLink" aria-expanded="false" aria-label="Toggle Navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarcollapseLink">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">About</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Project</a>
                </li>
            </ul>
        </div>
</nav>
{% endblock %}

{% block body %}
{% endblock %}

</body>
</html>

datainventory/templates/datainventory/detail.html
{% extends 'base.html' %}

{% block body %}
<h2>{{ instance.name }}</h2>
    <div class="container-fluid">
        <li>{{ instance.schema }}</li>
        <li>{{ instance.timestamp }}</li>
        <li>{{ instance.updated }}</li>
        <input type="hidden" id="schema" name="schema" value="{{ instance.schema }}">
        <input type="text" id="sampleData" value="{{ instance.sample }}" size="200"><br>
        <table class="table table-striped" id="sampleTable"><tbody></tbody></table>
    </div>
    <a href="{% url 'inventory:data_list' %}" class="btn btn-primary">Data inventory</a>
    <script type="text/javascript">
        $(function() {
            addTable($.parseJSON($("input#sampleData").val()),
                    $("table#sampleTable"),
                    $("input#schema"));
        });
    </script>
{% endblock %}

datainventory/templates/datainventory/list.html
{% extends 'base.html' %}
{% block body %}
    <div class="albums-container container-fluid">
        <div class="row">
            {% if object_list %}
                {% for object in object_list %}
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    <img class="card-img-top" src="http://www.runoob.com/wp-content/uploads/2014/06/kittens.jpg">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <h5 class="card-title">{{ object.name }}</h5>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <p class="card-text">{{ object.timestamp }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <a href="{% url 'inventory:data_detail' object.id %}" class="btn btn-primary">
                                        <span class="fa fa-bars"></span>
                                    </a>
                                    <button type="submit" class="btn btn-danger">
                                        <form action="#" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="dataset_id" value="{{ object.id }}" />
                                            <span class="fa fa-trash-o"></span>
                                        </form>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-sm-12">
                    <br>
                    <a href="#">
                        <button type="button" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a DataSet
                        </button>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}